//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace teat_WPF_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class apartments
    {
        public string Id { get; set; }
        public string Address_City { get; set; }
        public string Address_Street { get; set; }
        public int Address_House { get; set; }
        public string Address_Number { get; set; }
        public string Coordinate_latitude { get; set; }
        public string Coordinate_longitude { get; set; }
        public string TotalArea { get; set; }
        public string Rooms { get; set; }
        public string Floor { get; set; }
    }
}
