//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace teat_WPF_1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sessionsEntities : DbContext
    {
        private static sessionsEntities _context;
        public sessionsEntities()
            : base("name=sessionsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<apartments> apartments { get; set; }
        public DbSet<districts> districts { get; set; }
        public DbSet<houses> houses { get; set; }
        public DbSet<lands> lands { get; set; }
    }
}
